package com.pixie.mart.pixiemart.constants.enums;

public enum SellBicycleState {
    START_SELL, SENT_FOR_INSPECTION, INSPECTOR_ALLOCATED, INSPECTION_STARTED, INSPECTION_COMPLETED, PRICE_ESTIMATED,
    PAYMENT_APPROVED, PAYMENT_COMPLETED, PICKUP_COMPLETED
}
